const data = [
  {
    id: 1,
    title: 'Nhập Môn Lập Trình',
    teacher: 'Nguyễn Văn A',
    school_year: '2020 - 2021',
    img: require('./img/man.png') as string,
  },
  {
    id: 2,
    title: 'Phần Cứng Máy Tính',
    teacher: 'Nguyễn Văn B',
    school_year: '2020 - 2021',
    img: require('./img/gamer.png') as string,
  },
  {
    id: 3,
    title: 'Cở Sở Dữ Liệu',
    teacher: 'Nguyễn Văn B',
    school_year: '2020 - 2021',
    img: require('./img/woman1.png') as string,
  },
  {
    id: 4,
    title: 'Pháp Luật',
    teacher: 'Nguyễn Văn G',
    school_year: '2020 - 2021',
    img: require('./img/woman.png') as string,
  },
  {
    id: 5,
    title: 'Thiết Kế Website',
    teacher: 'Nguyễn Văn F',
    school_year: '2020 - 2021',
    img: require('./img/man1.png') as string,
  },
  {
    id: 6,
    title: 'HQT Cơ sở dữ liệu',
    teacher: 'Nguyễn Văn C',
    school_year: '2020 - 2021',
    img: require('./img/profile.png') as string,
  },
  {
    id: 7,
    title: 'Lập Trình Java',
    teacher: 'Nguyễn Văn A',
    school_year: '2020 - 2021',
    img: require('./img/woman.png') as string,
  },
  {
    id: 8,
    title: 'Lập Trình Di Động',
    teacher: 'Nguyễn Văn C',
    school_year: '2020 - 2021',
    img: require('./img/man.png') as string,
  },
  {
    id: 9,
    title: 'Lập Trình ASP .NET Core',
    teacher: 'Nguyễn Văn B',
    school_year: '2020 - 2021',
    img: require('./img/gamer.png') as string,
  },
  {
    id: 10,
    title: 'ĐATN',
    teacher: 'Nguyễn Văn A',
    school_year: '2020 - 2021',
    img: require('./img/profile.png') as string,
  },
];
export default data;
